import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import type { DashboardStats, SessionRecord, Student, Subject } from '@/types';

const SUBJECTS: Subject[] = ['math', 'reading', 'science', 'english', 'comprehension'];
const SUBJECT_LABELS: Record<Subject, string> = {
  math: 'Mathematics',
  reading: 'Reading',
  science: 'Science',
  english: 'English',
  comprehension: 'Comprehension',
};

function formatMonthYear(date: Date): string {
  return new Intl.DateTimeFormat('en-IN', {
    month: 'long',
    year: 'numeric',
  }).format(date);
}

function formatFileMonth(date: Date): string {
  return formatMonthYear(date).replace(/\s+/g, '-').toLowerCase();
}

function formatShortDate(date: Date): string {
  return new Intl.DateTimeFormat('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(date);
}

function addDarkPage(doc: jsPDF): void {
  doc.setFillColor(12, 15, 10);
  doc.rect(0, 0, 210, 297, 'F');
}

function averageGap(students: Student[], subject: Subject): number {
  if (students.length === 0) {
    return 0;
  }

  return students.reduce((sum, student) => sum + student.gap_profile[subject], 0) / students.length;
}

function sessionPreview(note: string): string {
  const trimmed = note.trim();

  if (!trimmed) {
    return 'No note recorded';
  }

  return trimmed.length > 60 ? `${trimmed.slice(0, 60)}...` : trimmed;
}

export function generateCSRReport(
  stats: DashboardStats,
  students: Student[],
  sessions: SessionRecord[],
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const now = new Date();
  const monthYear = formatMonthYear(now);
  const fileName = `vidyasetu-csr-${formatFileMonth(now)}.pdf`;
  const totalStudents = Math.max(stats.totalStudents, 1);
  const studentLookup = students.reduce<Record<string, string>>((accumulator, student) => {
    accumulator[student.id] = student.name;
    return accumulator;
  }, {});

  addDarkPage(doc);
  doc.setTextColor(184, 240, 74);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('VidyaSetu', 20, 50);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('Impact Report', 20, 70);

  doc.setFontSize(14);
  doc.setTextColor(180, 180, 180);
  doc.text(monthYear, 20, 85);
  doc.text('Youngistaan Foundation', 20, 95);
  doc.text('Generated by VidyaSetu | vidyasetu.app', 20, 105);

  doc.addPage();
  addDarkPage(doc);
  doc.setTextColor(184, 240, 74);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Section 1 - Program Reach', 20, 30);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(40);
  doc.text(String(stats.totalStudents), 20, 60);
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 180);
  doc.text('Total Students Enrolled', 20, 68);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(40);
  doc.text(String(stats.activeMentors), 80, 60);
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 180);
  doc.text('Active Volunteer Mentors', 80, 68);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(40);
  doc.text(String(stats.sessionsThisMonth), 20, 100);
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 180);
  doc.text('Sessions This Month', 20, 108);

  doc.addPage();
  addDarkPage(doc);
  doc.setTextColor(184, 240, 74);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Section 2 - Learning Gains', 20, 30);

  autoTable(doc, {
    startY: 45,
    head: [['Subject', 'Avg Gap Score', 'Status']],
    body: SUBJECTS.map((subject) => {
      const avgGap = averageGap(students, subject);
      const status = avgGap < 2 ? 'Good' : avgGap < 3.5 ? 'Improving' : 'Needs Attention';
      return [SUBJECT_LABELS[subject], avgGap.toFixed(2), status];
    }),
    styles: { fillColor: [20, 20, 20], textColor: [255, 255, 255] },
    headStyles: { fillColor: [184, 240, 74], textColor: [0, 0, 0] },
  });

  doc.addPage();
  addDarkPage(doc);
  doc.setTextColor(184, 240, 74);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Section 3 - Parent Engagement', 20, 30);

  const engagementRate = Math.round(stats.parentEngagementRate * 100);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(40);
  doc.text(`${engagementRate}%`, 20, 60);
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 180);
  doc.text('Parent SMS Reply Rate', 20, 68);

  doc.setFontSize(12);
  doc.setTextColor(200, 200, 200);
  doc.text('VidyaSetu sends session alerts to parents via SMS in their native language.', 20, 85);
  doc.text('(Hindi, Telugu, or English). Parents reply with a single letter:', 20, 93);
  doc.text('H for Happy | C for Concern', 20, 101);

  doc.addPage();
  addDarkPage(doc);
  doc.setTextColor(184, 240, 74);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Section 4 - Student Risk Distribution', 20, 30);

  autoTable(doc, {
    startY: 45,
    head: [['Risk Level', 'Student Count', 'Percentage']],
    body: [
      ['Green (Safe)', String(stats.greenCount), `${Math.round((stats.greenCount / totalStudents) * 100)}%`],
      ['Amber (Monitor)', String(stats.amberCount), `${Math.round((stats.amberCount / totalStudents) * 100)}%`],
      ['Red (High Risk)', String(stats.redCount), `${Math.round((stats.redCount / totalStudents) * 100)}%`],
    ],
    styles: { fillColor: [20, 20, 20], textColor: [255, 255, 255] },
    headStyles: { fillColor: [184, 240, 74], textColor: [0, 0, 0] },
  });

  const recentSessions = [...sessions]
    .sort((left, right) => new Date(right.session_date).getTime() - new Date(left.session_date).getTime())
    .slice(0, 5);

  if (recentSessions.length > 0) {
    autoTable(doc, {
      startY: 110,
      head: [['Date', 'Student', 'Session Note']],
      body: recentSessions.map((session) => [
        formatShortDate(new Date(session.session_date)),
        studentLookup[session.student_id] ?? session.student_id,
        sessionPreview(session.note),
      ]),
      styles: { fillColor: [20, 20, 20], textColor: [255, 255, 255], fontSize: 9 },
      headStyles: { fillColor: [60, 60, 60], textColor: [255, 255, 255] },
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(
      `Report generated by VidyaSetu | vidyasetu.app | ${formatShortDate(now)} | Page ${page} of ${pageCount}`,
      20,
      287,
    );
  }

  doc.save(fileName);
}
